baseURL = "https://yiyang-hsu.github.io/HN-hugo/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableGitInfo = true
pluralizeListTitles = true
theme = "HN-hugo"
title = "HN-hugo Demo"
themesDir = "../../"

[languages]

[languages.zh]
languageName = "简体"
weight = 2
[languages.zht]
languageName = "繁體"
weight = 1
[languages.en]
languageName = "English"
weight = 0

[imaging]
quality = 100
